s2e_env: fixed basic_block.py infinite loop
S2E/s2e-env pull request #449
Opened 2021-12-07 05:20 UTC by BMorgan1296

Signed-off-by: Bradley Morgan <compsec@bradm.io>

2021-12-07 05:21 UTC, BMorgan1296 commented
There were only two deprecation warnings from the output of `test.sh`, unrelated to my changes.

2021-12-07 10:21 UTC, vitalych commented on s2e_env/commands/code_coverage/basic_block.py
> +            lo = mid + 1
Thanks, it looks better than this previously abandonned PR.
https://github.com/S2E/s2e-env/pull/255/commits/444a884d2af57552bbcddcdaf7c0fac9b557a59d

Could you make all the loop conditions exactly like on wikipedia? Something like this:

```
if A[m] < T then
    L := m + 1
else if A[m] > T then
    R := m − 1
else:
    return m
``` 

Currently we have `bbs[mid - 1].end_addr < tb_start_addr <= bbs[mid].end_addr:` and `tb_start_addr <= bbs[mid].end_addr` and I can't easily reason about its correctness.

A unit test would also be useful.

2021-12-08 03:32 UTC, BMorgan1296 commented on s2e_env/commands/code_coverage/basic_block.py
> +            lo = mid + 1
How would you like the unit test to be structured? I've been using Radare2 as my disassembler. Is it suitable to force its use in such a test?

2021-12-08 10:35 UTC, vitalych commented on s2e_env/commands/code_coverage/basic_block.py
> +            lo = mid + 1
No, using the real radare2 would be an integration test. For the unit test, you'd just have to simulate the input to the function that causes the bug. You could dump it by printing the arguments that caused the original function to hang.

2021-12-09 23:11 UTC, vitalych commented on s2e_env/commands/code_coverage/basic_block.py
> +        #print(dir(self._project_dir))
Don't leave commented out code

2021-12-09 23:13 UTC, vitalych commented on tests/commands/code_coverage/test_bb_code_coverage_elf.py
> +        file1 = open('tests/commands/code_coverage/mmount_bbs.obj', 'rb')
Would it be possible to avoid pickled files? Besides security issues, they are hard to edit. Use Python code instead.

2021-12-09 23:14 UTC, vitalych commented on tests/commands/code_coverage/test_bb_code_coverage_elf.py
> +        bbs = tb_coverage = None
Squash this commit. Pull requests should not have fixes to their own code.

2021-12-09 23:15 UTC, vitalych requested changes
see comments

2021-12-09 23:21 UTC, vitalych commented on tests/commands/code_coverage/__init__.py
> +CURR_DIR = os.path.join(os.getcwd(), os.path.dirname(__file__))
I wouldn't use getcwd(), it forces the tests to be run from a specific directory.

2021-12-13 03:19 UTC, BMorgan1296 commented on tests/commands/code_coverage/test_bb_code_coverage_elf.py
> +        bbs = tb_coverage = None
Done.

2021-12-13 09:43 UTC, vitalych commented
Force-pushing is the proper method to handle this. It's your private branch, so force-push is fine. It's important to do this because it makes it easier for reviewers. A reviewer might spend time commenting on some code issue only to find in a later commit that this issue was resolved. 

Note that you shouldn't necessarily force-push everything into one commit either. They still must be logically split, again, to make it easier to review. In this particular case, if you find yourself calling the commit `fixed basic_block.py infinite loop, added unit test, fixed a dict field error`, you would probably need one commit for each fix:
1. infinite loop
2. dict error
3. added unit tests

2021-12-13 09:44 UTC, vitalych commented on tests/commands/code_coverage/mmount_tb_coverage.json
> +{"./mmount": [[16384, 16402, 20], [16406, 16410, 5], [18864, 18868, 11], [18896, 18900, 11], [18912, 18916, 11], [19120, 19124, 11], [19488, 19492, 11], [19584, 19588, 11], [19680, 19684, 11], [19936
This looks good

2021-12-13 09:58 UTC, vitalych commented on tests/commands/code_coverage/test_bb_code_coverage_elf.py
> +        with open(CURR_DIR+'/mmount_bbs.json', 'r') as f1:
You might need to add `encoding='utf-8'` to open. I was getting pylint warnings.

2021-12-14 10:11 UTC, vitalych commented on tests/commands/code_coverage/test_bb_code_coverage_elf.py
> +        with open(CURR_DIR+'/mmount_bbs.json', 'r') as f1:
`os.path.join()` would be better

2021-12-14 10:12 UTC, vitalych approved these changes
one last small remark

2021-12-15 10:49 UTC, merged